// <auto-generated />
using System;
using System.Collections.Generic;
using GRIF.DataBaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GRIF.Migrations.ExchangeUpload
{
    [DbContext(typeof(ExchangeUploadContext))]
    [Migration("20260218134255_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GRIF.Entities.DocumentBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DocumentPartId")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfEditing")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentPartId");

                    b.ToTable("DocumentBlock");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DocumentBlock");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GRIF.Entities.DocumentPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModelDocumentWordId")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfEditing")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModelDocumentWordId");

                    b.ToTable("DocumentParts");
                });

            modelBuilder.Entity("GRIF.Entities.ModelDocumentWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfEditing")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ModelDocumentWord");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ModelDocumentWord");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GRIF.Entities.RowFootnote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("Column")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("TableRowId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TableRowId")
                        .IsUnique();

                    b.ToTable("RowFootnote");
                });

            modelBuilder.Entity("GRIF.Entities.TableRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Columns")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("FootnoteId")
                        .HasColumnType("integer");

                    b.Property<int>("HashCode")
                        .HasColumnType("integer");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TableBlockId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TableBlockId");

                    b.ToTable("TableRows");
                });

            modelBuilder.Entity("GostObjectsClassLibrary.TableFootnote", b =>
                {
                    b.Property<Guid>("FootNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Column")
                        .HasColumnType("integer");

                    b.Property<int?>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("FootNoteId");

                    b.ToTable("TableFootnotes");
                });

            modelBuilder.Entity("GRIF.Entities.TableBlock", b =>
                {
                    b.HasBaseType("GRIF.Entities.DocumentBlock");

                    b.Property<string>("BookmarkName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("ColumnHeaders")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasDiscriminator().HasValue("TableBlock");
                });

            modelBuilder.Entity("GRIF.Entities.TextBlock", b =>
                {
                    b.HasBaseType("GRIF.Entities.DocumentBlock");

                    b.Property<string>("BookmarkName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("DocumentBlock", t =>
                        {
                            t.Property("BookmarkName")
                                .HasColumnName("TextBlock_BookmarkName");
                        });

                    b.HasDiscriminator().HasValue("TextBlock");
                });

            modelBuilder.Entity("GRIF.Entities.ExchangeDocumentWord", b =>
                {
                    b.HasBaseType("GRIF.Entities.ModelDocumentWord");

                    b.HasDiscriminator().HasValue("ExchangeDocumentWord");
                });

            modelBuilder.Entity("GRIF.Entities.DocumentBlock", b =>
                {
                    b.HasOne("GRIF.Entities.DocumentPart", "DocumentPart")
                        .WithMany("Blocks")
                        .HasForeignKey("DocumentPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentPart");
                });

            modelBuilder.Entity("GRIF.Entities.DocumentPart", b =>
                {
                    b.HasOne("GRIF.Entities.ModelDocumentWord", "ModelDocumentWord")
                        .WithMany("Parts")
                        .HasForeignKey("ModelDocumentWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelDocumentWord");
                });

            modelBuilder.Entity("GRIF.Entities.RowFootnote", b =>
                {
                    b.HasOne("GRIF.Entities.TableRow", "TableRow")
                        .WithOne("Footnote")
                        .HasForeignKey("GRIF.Entities.RowFootnote", "TableRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableRow");
                });

            modelBuilder.Entity("GRIF.Entities.TableRow", b =>
                {
                    b.HasOne("GRIF.Entities.TableBlock", "TableBlock")
                        .WithMany("Rows")
                        .HasForeignKey("TableBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableBlock");
                });

            modelBuilder.Entity("GRIF.Entities.DocumentPart", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("GRIF.Entities.ModelDocumentWord", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("GRIF.Entities.TableRow", b =>
                {
                    b.Navigation("Footnote");
                });

            modelBuilder.Entity("GRIF.Entities.TableBlock", b =>
                {
                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
